### PR TITLE
[LOOP-1125] Upload pump data

### PR DESCRIPTION
**Pull request by darinkrauss**
- https://tidepool.atlassian.net/browse/LOOP-1125
- https://tidepool.atlassian.net/browse/LOOP-1124
- Add automated bolus data type
- Add suppressed to automated basal data type
- Update tests

### CODE REVIEW

**Review by nhamming — APPROVED** [review]
LGTM

**Comment by darinkrauss** [comment]
LW PR for build: https://github.com/tidepool-org/LoopWorkspace/pull/741

**Review by rickpasetto — APPROVED** [review]
LGTM

**Review by ps2 — APPROVED** [review]
LGTM!

**Pull request merged**
